### ISSUE TITLE
trouble building quip_tools

### ISSUE THREAD

**Issue by wakamex** [Cornell-RelaxML/quip-sharp#25]
do I need a specific compiler version?

I'm using gcc 13.2

```
gcc --version
gcc (Ubuntu 13.2.0-4ubuntu3) 13.2.0
Copyright (C) 2023 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

I think it's picking up the cuda 12.0 in my `/usr/bin` though the python requirements show CUDA 12.1.

I also didn't see anything about the python version, so I tried with 3.10 and 3.11.

```
cd quiptools && python setup.py install && cd ../
running install
/home/mihai/.pyenv/versions/quip/lib/python3.11/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
/home/mihai/.pyenv/versions/quip/lib/python3.11/site-packages/setuptools/command/easy_install.py:144: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
running bdist_egg
running egg_info
writing quiptools_cuda.egg-info/PKG-INFO
writing dependency_links to quiptools_cuda.egg-info/dependency_links.txt
writing top-level names to quiptools_cuda.egg-info/top_level.txt
reading manifest file 'quiptools_cuda.egg-info/SOURCES.txt'
writing manifest file 'quiptools_cuda.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_ext
/home/mihai/.pyenv/versions/quip/lib/python3.11/site-packages/torch/utils/cpp_extension.py:414: UserWarning: The detected CUDA version (12.0) has a minor version mismatch with the version that was used to compile PyTorch (12.1). Most likely this shouldn't be a problem.
  warnings.warn(CUDA_MISMATCH_WARN.format(cuda_str_version, torch.version.cuda))
/home/mihai/.pyenv/versions/quip/lib/python3.11/site-packages/torch/utils/cpp_extension.py:424: UserWarning: There are no g++ version bounds defined for CUDA version 12.0
  warnings.warn(f'There are no {compiler_name} version bounds defined for CUDA version {cuda_str_version}')
building 'quiptools_cuda' extension
Emitting ninja build file /code/quip-sharp/quiptools/build/temp.linux-x86_64-cpython-311/build.ninja...
Compiling objects...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
[1/2] /usr/bin/nvcc  -I/home/mihai/.pyenv/versions/quip/lib/python3.11/site-packages/torch/include -I/home/mihai/.pyenv/versions/quip/lib/python3.11/site-packages/torch/include/torch/csrc/api/include -I/home/mihai/.pyenv/versions/quip/lib/python3.11/site-packages/torch/include/TH -I/home/mihai/.pyenv/versions/quip/lib/python3.11/site-packages/torch/include/THC -I/home/mihai/.pyenv/versions/quip/include -I/home/mihai/.pyenv/versions/3.11.7/include/python3.11 -c -c /code/quip-sharp/quiptools/quiptools.cu -o /code/quip-sharp/quiptools/build/temp.linux-x86_64-cpython-311/quiptools.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -O2 -g -Xcompiler -rdynamic -lineinfo -allow-unsupported-compiler -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=quiptools_cuda -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_86,code=compute_86 -gencode=arch=compute_86,code=sm_86 -std=c++17
FAILED: /code/quip-sharp/quiptools/build/temp.linux-x86_64-cpython-311/quiptools.o 
/usr/bin/nvcc  -I/home/mihai/.pyenv/versions/quip/lib/python3.11/site-packages/torch/include -I/home/mihai/.pyenv/versions/quip/lib/python3.11/site-packages/torch/include/torch/csrc/api/include -I/home/mihai/.pyenv/versions/quip/lib/python3.11/site-packages/torch/include/TH -I/home/mihai/.pyenv/versions/quip/lib/python3.11/site-packages/torch/include/THC -I/home/mihai/.pyenv/versions/quip/include -I/home/mihai/.pyenv/versions/3.11.7/include/python3.11 -c -c /code/quip-sharp/quiptools/quiptools.cu -o /code/quip-sharp/quiptools/build/temp.linux-x86_64-cpython-311/quiptools.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -O2 -g -Xcompiler -rdynamic -lineinfo -allow-unsupported-compiler -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=quiptools_cuda -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_86,code=compute_86 -gencode=arch=compute_86,code=sm_86 -std=c++17
/code/quip-sharp/quiptools/quiptools.cu(34): warning #177-D: function "gpuAssert" was declared but never referenced

Remark: The warnings can be suppressed with "-diag-suppress <warning-number>"

/home/mihai/.pyenv/versions/quip/lib/python3.11/site-packages/torch/include/pybind11/detail/../cast.h: In function ‘typename pybind11::detail::type_caster<typename pybind11::detail::intrinsic_type<T>::type>::cast_op_type<T> pybind11::detail::cast_op(make_caster<T>&)’:
/home/mihai/.pyenv/versions/quip/lib/python3.11/site-packages/torch/include/pybind11/detail/../cast.h:45:120: error: expected template-name before ‘<’ token
   45 |     return caster.operator typename make_caster<T>::template cast_op_type<T>();
      |                                                                                                                        ^
/home/mihai/.pyenv/versions/quip/lib/python3.11/site-packages/torch/include/pybind11/detail/../cast.h:45:120: error: expected identifier before ‘<’ token
/home/mihai/.pyenv/versions/quip/lib/python3.11/site-packages/torch/include/pybind11/detail/../cast.h:45:123: error: expected primary-expression before ‘>’ token
   45 |     return caster.operator typename make_caster<T>::template cast_op_type<T>();
      |                                                                                                                           ^
/home/mihai/.pyenv/versions/quip/lib/python3.11/site-packages/torch/include/pybind11/detail/../cast.h:45:126: error: expected primary-expression before ‘)’ token
   45 |     return caster.operator typename make_caster<T>::template cast_op_type<T>();
      |                                                                                                                              ^
[2/2] /usr/bin/nvcc  -I/home/mihai/.pyenv/versions/quip/lib/python3.11/site-packages/torch/include -I/home/mihai/.pyenv/versions/quip/lib/python3.11/site-packages/torch/include/torch/csrc/api/include -I/home/mihai/.pyenv/versions/quip/lib/python3.11/site-packages/torch/include/TH -I/home/mihai/.pyenv/versions/quip/lib/python3.11/site-packages/torch/include/THC -I/home/mihai/.pyenv/versions/quip/include -I/home/mihai/.pyenv/versions/3.11.7/include/python3.11 -c -c /code/quip-sharp/quiptools/quiptools_e8p_gemv.cu -o /code/quip-sharp/quiptools/build/temp.linux-x86_64-cpython-311/quiptools_e8p_gemv.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -O2 -g -Xcompiler -rdynamic -lineinfo -allow-unsupported-compiler -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=quiptools_cuda -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_86,code=compute_86 -gencode=arch=compute_86,code=sm_86 -std=c++17
FAILED: /code/quip-sharp/quiptools/build/temp.linux-x86_64-cpython-311/quiptools_e8p_gemv.o 
/usr/bin/nvcc  -I/home/mihai/.pyenv/versions/quip/lib/python3.11/site-packages/torch/include -I/home/mihai/.pyenv/versions/quip/lib/python3.11/site-packages/torch/include/torch/csrc/api/include -I/home/mihai/.pyenv/versions/quip/lib/python3.11/site-packages/torch/include/TH -I/home/mihai/.pyenv/versions/quip/lib/python3.11/site-packages/torch/include/THC -I/home/mihai/.pyenv/versions/quip/include -I/home/mihai/.pyenv/versions/3.11.7/include/python3.11 -c -c /code/quip-sharp/quiptools/quiptools_e8p_gemv.cu -o /code/quip-sharp/quiptools/build/temp.linux-x86_64-cpython-311/quiptools_e8p_gemv.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -O2 -g -Xcompiler -rdynamic -lineinfo -allow-unsupported-compiler -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=quiptools_cuda -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_86,code=compute_86 -gencode=arch=compute_86,code=sm_86 -std=c++17
/code/quip-sharp/quiptools/quiptools_e8p_gemv.cu(85): warning #177-D: variable "shared_weights" was declared but never referenced

Remark: The warnings can be suppressed with "-diag-suppress <warning-number>"

/home/mihai/.pyenv/versions/quip/lib/python3.11/site-packages/torch/include/pybind11/detail/../cast.h: In function ‘typename pybind11::detail::type_caster<typename pybind11::detail::intrinsic_type<T>::type>::cast_op_type<T> pybind11::detail::cast_op(make_caster<T>&)’:
/home/mihai/.pyenv/versions/quip/lib/python3.11/site-packages/torch/include/pybind11/detail/../cast.h:45:120: error: expected template-name before ‘<’ token
   45 |     return caster.operator typename make_caster<T>::template cast_op_type<T>();
      |                                                                                                                        ^
/home/mihai/.pyenv/versions/quip/lib/python3.11/site-packages/torch/include/pybind11/detail/../cast.h:45:120: error: expected identifier before ‘<’ token
/home/mihai/.pyenv/versions/quip/lib/python3.11/site-packages/torch/include/pybind11/detail/../cast.h:45:123: error: expected primary-expression before ‘>’ token
   45 |     return caster.operator typename make_caster<T>::template cast_op_type<T>();
      |                                                                                                                           ^
/home/mihai/.pyenv/versions/quip/lib/python3.11/site-packages/torch/include/pybind11/detail/../cast.h:45:126: error: expected primary-expression before ‘)’ token
   45 |     return caster.operator typename make_caster<T>::template cast_op_type<T>();
      |                                                                                                                              ^
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "/home/mihai/.pyenv/versions/quip/lib/python3.11/site-packages/torch/utils/cpp_extension.py", line 2100, in _run_ninja_build
    subprocess.run(
  File "/home/mihai/.pyenv/versions/3.11.7/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/code/quip-sharp/quiptools/setup.py", line 4, in <module>
    setup(name='quiptools_cuda',
  File "/home/mihai/.pyenv/versions/quip/lib/python3.11/site-packages/setuptools/__init__.py", line 87, in setup
    return distutils.core.setup(**attrs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mihai/.pyenv/versions/quip/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 185, in setup
    return run_commands(dist)
           ^^^^^^^^^^^^^^^^^^
  File "/home/mihai/.pyenv/versions/quip/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
    dist.run_commands()
  File "/home/mihai/.pyenv/versions/quip/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 968, in run_commands
    self.run_command(cmd)
  File "/home/mihai/.pyenv/versions/quip/lib/python3.11/site-packages/setuptools/dist.py", line 1217, in run_command
    super().run_command(command)
  File "/home/mihai/.pyenv/versions/quip/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 987, in run_command
    cmd_obj.run()
  File "/home/mihai/.pyenv/versions/quip/lib/python3.11/site-packages/setuptools/command/install.py", line 74, in run
    self.do_egg_install()
  File "/home/mihai/.pyenv/versions/quip/lib/python3.11/site-packages/setuptools/command/install.py", line 123, in do_egg_install
    self.run_command('bdist_egg')
  File "/home/mihai/.pyenv/versions/quip/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 319, in run_command
    self.distribution.run_command(command)
  File "/home/mihai/.pyenv/versions/quip/lib/python3.11/site-packages/setuptools/dist.py", line 1217, in run_command
    super().run_command(command)
  File "/home/mihai/.pyenv/versions/quip/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 987, in run_command
    cmd_obj.run()
  File "/home/mihai/.pyenv/versions/quip/lib/python3.11/site-packages/setuptools/command/bdist_egg.py", line 165, in run
    cmd = self.call_command('install_lib', warn_dir=0)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mihai/.pyenv/versions/quip/lib/python3.11/site-packages/setuptools/command/bdist_egg.py", line 151, in call_command
    self.run_command(cmdname)
  File "/home/mihai/.pyenv/versions/quip/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 319, in run_command
    self.distribution.run_command(command)
  File "/home/mihai/.pyenv/versions/quip/lib/python3.11/site-packages/setuptools/dist.py", line 1217, in run_command
    super().run_command(command)
  File "/home/mihai/.pyenv/versions/quip/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 987, in run_command
    cmd_obj.run()
  File "/home/mihai/.pyenv/versions/quip/lib/python3.11/site-packages/setuptools/command/install_lib.py", line 11, in run
    self.build()
  File "/home/mihai/.pyenv/versions/quip/lib/python3.11/site-packages/setuptools/_distutils/command/install_lib.py", line 112, in build
    self.run_command('build_ext')
  File "/home/mihai/.pyenv/versions/quip/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 319, in run_command
    self.distribution.run_command(command)
  File "/home/mihai/.pyenv/versions/quip/lib/python3.11/site-packages/setuptools/dist.py", line 1217, in run_command
    super().run_command(command)
  File "/home/mihai/.pyenv/versions/quip/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 987, in run_command
    cmd_obj.run()
  File "/home/mihai/.pyenv/versions/quip/lib/python3.11/site-packages/setuptools/command/build_ext.py", line 84, in run
    _build_ext.run(self)
  File "/home/mihai/.pyenv/versions/quip/lib/python3.11/site-packages/setuptools/_distutils/command/build_ext.py", line 346, in run
    self.build_extensions()
  File "/home/mihai/.pyenv/versions/quip/lib/python3.11/site-packages/torch/utils/cpp_extension.py", line 873, in build_extensions
    build_ext.build_extensions(self)
  File "/home/mihai/.pyenv/versions/quip/lib/python3.11/site-packages/setuptools/_distutils/command/build_ext.py", line 466, in build_extensions
    self._build_extensions_serial()
  File "/home/mihai/.pyenv/versions/quip/lib/python3.11/site-packages/setuptools/_distutils/command/build_ext.py", line 492, in _build_extensions_serial
    self.build_extension(ext)
  File "/home/mihai/.pyenv/versions/quip/lib/python3.11/site-packages/setuptools/command/build_ext.py", line 246, in build_extension
    _build_ext.build_extension(self, ext)
  File "/home/mihai/.pyenv/versions/quip/lib/python3.11/site-packages/setuptools/_distutils/command/build_ext.py", line 547, in build_extension
    objects = self.compiler.compile(
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mihai/.pyenv/versions/quip/lib/python3.11/site-packages/torch/utils/cpp_extension.py", line 686, in unix_wrap_ninja_compile
    _write_ninja_file_and_compile_objects(
  File "/home/mihai/.pyenv/versions/quip/lib/python3.11/site-packages/torch/utils/cpp_extension.py", line 1774, in _write_ninja_file_and_compile_objects
    _run_ninja_build(
  File "/home/mihai/.pyenv/versions/quip/lib/python3.11/site-packages/torch/utils/cpp_extension.py", line 2116, in _run_ninja_build
    raise RuntimeError(message) from e
RuntimeError: Error compiling objects for extension
```

**Comment by tsengalb99** [comment]
Your cuda compiler version should match your pytorch cuda version and I think you need a recent cuda (>=11.x?) but otherwise it should work with things not cuda 12.1.

**Comment by wakamex** [comment]
Thanks, I got it to compile with cuda 11.8 and gcc 11 (latest compatible with cuda 11.8).

**Comment by YangWang92** [comment]
@wakamex I got the same problem, and you can update setup.py to set arch to bypass the compile error.

```
setup(name='quiptools_cuda',
      ext_modules=[cpp_extension.CUDAExtension(
          'quiptools_cuda',
          ['quiptools_wrapper.cpp', 'quiptools.cu', 'quiptools_e8p_gemv.cu'],
          extra_compile_args={'cxx': ['-g', '-lineinfo'],
                              'nvcc': ['-O2', '-g', '-Xcompiler', '-rdynamic', '-lineinfo',
                                       '-gencode=arch=compute_70,code=sm_70',
                                       '-gencode=arch=compute_80,code=sm_80']})],
      cmdclass={'build_ext': cpp_extension.BuildExtension})
```
