### ISSUE TITLE
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

### ISSUE THREAD

**Issue by Minami-su** [Cornell-RelaxML/quip-sharp#4]
```
(train) root@WIN-IUEXHKJBZLU:/home/luhao/quip-sharp# CUDA_VISIBLE_DEVICES=0 python quantize_llama.py --base_model Yi-34B-Chat --codebook E8P12
Loading checkpoint shards: 100%|████████████████████████████████████████████████████████| 15/15 [00:01<00:00, 10.49it/s]
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
I1204 12:02:37.810840 3560 quantize_llama.py:289] loaded model
W1204 12:02:40.726335 3560 warnings.py:109] /root/anaconda3/envs/train/lib/python3.9/site-packages/datasets/table.py:1421: FutureWarning: promote has been superseded by mode='default'.
  table = cls._concat_blocks(blocks, axis=0)

8
18
26
33
38
51
63
64
I1204 12:02:50.217392 3560 quantize_llama.py:293] loaded dataset and devset
Traceback (most recent call last):
  File "/home/luhao/quip-sharp/quantize_llama.py", line 417, in <module>
    main(args)
  File "/home/luhao/quip-sharp/quantize_llama.py", line 342, in main
    model.model.layers[i](
  File "/root/anaconda3/envs/train/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/root/anaconda3/envs/train/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/anaconda3/envs/train/lib/python3.9/site-packages/transformers/models/llama/modeling_llama.py", line 635, in forward
    hidden_states, self_attn_weights, present_key_value = self.self_attn(
  File "/root/anaconda3/envs/train/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/root/anaconda3/envs/train/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/anaconda3/envs/train/lib/python3.9/site-packages/transformers/models/llama/modeling_llama.py", line 389, in forward
    attn_weights = nn.functional.softmax(attn_weights, dim=-1, dtype=torch.float32).to(query_states.dtype)
  File "/root/anaconda3/envs/train/lib/python3.9/site-packages/torch/nn/functional.py", line 1858, in softmax
    ret = input.softmax(dim, dtype=dtype)
RuntimeError: CUDA error: unknown error
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
```

**Comment by Minami-su** [comment]
transformers==4.34

**Comment by tsengalb99** [comment]
That's not a very useful error message. Furthermore, the stack trace appears to be completely in huggingface's code. Have you verified that this model works outside of the quip# codebase?

**Comment by luke-mcdermott-mi** [comment]
Same issue, but --batch size 1 does not solve this. For @tsengalb99's comment, I have been able to load relaxml/Mistral-7b-E8P-2Bit outside of this codebase, but the outputs are gibberish / load random weights (i assumed because it needs the codebook).
